#!/bin/bash
#
# Mac mini server setup script.
# Run once on a new Mac mini, or use flags to toggle sleep mode.
#
# Usage:
#   scripts/mac-mini-setup.sh           # full setup (server mode, no sleep)
#   scripts/mac-mini-setup.sh --sleep   # re-enable normal sleep (laptop mode)
#   scripts/mac-mini-setup.sh --sleep-only  # server mode sleep only, skip Immich setup

set -uo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL_CONFIG="$HOME/.config/dotfiles/mac-mini.conf"

log_ok()     { echo -e "${GREEN}✓${NC} $1"; }
log_warn()   { echo -e "${YELLOW}⚠${NC} $1"; }
log_error()  { echo -e "${RED}✗${NC} $1"; }
log_header() {
  echo -e "\n${BLUE}========================================${NC}"
  echo -e "${BLUE}  $1${NC}"
  echo -e "${BLUE}========================================${NC}"
}

# -------------------------------------------------------
# Sleep settings
# -------------------------------------------------------

enable_server_sleep() {
  log_header "Server Mode — Disabling Sleep"
  sudo pmset -a sleep 0 disksleep 0 displaysleep 10
  sudo systemsetup -setrestartpowerfailure on
  log_ok "Machine will never sleep (screen off after 10min)"
  log_ok "Auto-restart after power failure enabled"
}

reset_sleep() {
  log_header "Resetting Sleep to Normal"
  sudo pmset -a sleep 1
  log_ok "Normal sleep restored"
}

# -------------------------------------------------------
# Local config (stores T7 volume name for scripts to reuse)
# -------------------------------------------------------

write_local_config() {
  local volume_name="$1"
  mkdir -p "$(dirname "$LOCAL_CONFIG")"
  cat > "$LOCAL_CONFIG" <<EOF
# Mac mini local config — generated by mac-mini-setup.sh
# Do not commit this file.
IMMICH_VOLUME="$volume_name"
EOF
  log_ok "Saved volume name to $LOCAL_CONFIG"
}

# -------------------------------------------------------
# Immich setup
# -------------------------------------------------------

setup_immich() {
  log_header "Setting Up Immich"

  echo "Available volumes on /Volumes:"
  ls /Volumes/
  echo ""
  read -r -p "Enter your T7 volume name (the one with your photos): " T7_NAME

  if [ ! -d "/Volumes/$T7_NAME" ]; then
    log_error "/Volumes/$T7_NAME not found — check the name and rerun"
    exit 1
  fi

  # Save to local config so backup-immich.sh can read it
  write_local_config "$T7_NAME"

  # Create folders
  mkdir -p "/Volumes/$T7_NAME/immich"
  mkdir -p ~/services/immich
  mkdir -p ~/logs
  log_ok "Folders created"

  # Copy docker-compose.yml with volume name substituted
  local compose_src="$DOTFILES_DIR/config/immich/docker-compose.yml"
  local compose_dst="$HOME/services/immich/docker-compose.yml"

  if [ -f "$compose_dst" ]; then
    log_warn "docker-compose.yml already exists at $compose_dst — skipping"
  else
    sed "s|{{IMMICH_VOLUME}}|$T7_NAME|g" "$compose_src" > "$compose_dst"
    log_ok "docker-compose.yml written to ~/services/immich/"
  fi

  # Copy .env.example if .env doesn't exist
  local env_src="$DOTFILES_DIR/config/immich/.env.example"
  local env_dst="$HOME/services/immich/.env"

  if [ -f "$env_dst" ]; then
    log_warn ".env already exists — skipping"
  else
    cp "$env_src" "$env_dst"
    log_ok ".env copied to ~/services/immich/"
    log_warn "Edit ~/services/immich/.env and set a real DB_PASSWORD before starting Immich"
  fi
}

# -------------------------------------------------------
# Main
# -------------------------------------------------------

main() {
  local mode="${1:-full}"

  case "$mode" in
    --sleep)
      reset_sleep
      ;;
    --sleep-only)
      enable_server_sleep
      ;;
    full|*)
      enable_server_sleep
      setup_immich
      log_header "Done"
      echo "Next steps:"
      echo "  1) Edit ~/services/immich/.env — set DB_PASSWORD"
      echo "  2) cd ~/services/immich && docker compose up -d"
      echo "  3) Open http://<tailscale-ip>:2283 to create your account"
      ;;
  esac
}

main "${1:-}"
