#!/bin/bash
# Serve a directory over plain HTTP on the LAN and generate a one-command
# installer the Kindle can run, instead of typing a wget line per file.
#
#   ~/.dotfiles/scripts/books/serve-to-kindle.sh [directory] [port]
#
# On the Kindle you then run a single line in kTerm:
#
#   wget -O /tmp/i.sh http://<ip>:<port>/_install.sh && sh /tmp/i.sh
#
# Why this exists: getting files onto a modern Kindle is awkward on macOS.
#
#   * USB doesn't work — Kindles from ~2022 (Scribe included) present as MTP,
#     which macOS cannot mount without third-party software.
#   * Downloading on-device from GitHub doesn't work either — the Kindle's
#     busybox `wget` can't negotiate the TLS their CDN requires, so HTTPS
#     downloads die with "Connection reset by peer".
#
# Plain HTTP over the LAN sidesteps both. The server runs only while this script
# is in the foreground, binds to the local network, and serves read-only.

set -uo pipefail

DIR="${1:-$HOME/Downloads/kindle-plugins}"
PORT="${2:-8765}"

GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'; NC='\033[0m'

[[ -d "$DIR" ]] || { echo "No such directory: $DIR"; exit 1; }

IP="$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null)"
[[ -n "$IP" ]] || { echo "Could not determine a LAN IP — are you on Wi-Fi?"; exit 1; }

BASE="http://$IP:$PORT"
INSTALLER="$DIR/_install.sh"

# The installer runs under the Kindle's busybox shell: keep it POSIX, no
# bashisms. It skips anything already present, so re-running is safe.
{
  echo '#!/bin/sh'
  echo '# Generated by serve-to-kindle.sh — safe to re-run, skips existing files.'
  echo 'set -u'
  echo 'BASE="'"$BASE"'"'
  echo 'PLUGINS=/mnt/us/koreader/plugins'
  echo 'SAVERS=/mnt/us/screensavers'
  echo 'mkdir -p "$PLUGINS" "$SAVERS"'
  echo 'ok=0; skip=0; fail=0'
  echo ''
  echo 'get() {  # get <remote-name> <destination-path>'
  echo '  if [ -e "$2" ]; then echo "  = $(basename "$2") already there"; skip=$((skip+1)); return 0; fi'
  echo '  if wget -q -O "$2.part" "$BASE/$1"; then'
  echo '    mv "$2.part" "$2"; echo "  + $(basename "$2")"; ok=$((ok+1))'
  echo '  else'
  echo '    rm -f "$2.part"; echo "  ! FAILED $1"; fail=$((fail+1))'
  echo '  fi'
  echo '}'
  echo ''
  echo 'unpack() {  # unpack <zip-path> <target-dir> <marker-inside>'
  echo '  if [ -e "$3" ]; then echo "  = $(basename "$3") already installed"; skip=$((skip+1)); rm -f "$1"; return 0; fi'
  echo '  if ( cd "$2" && unzip -oq "$1" ); then echo "  > unpacked into $2"; ok=$((ok+1)); rm -f "$1"'
  echo '  else echo "  ! unzip failed for $1"; fail=$((fail+1)); fi'
  echo '}'
  echo ''

  shopt -s nullglob
  for f in "$DIR"/*; do
    [[ -f "$f" ]] || continue
    name="$(basename "$f")"
    [[ "$name" == "_install.sh" ]] && continue
    case "$name" in
      *.png|*.jpg|*.jpeg)
        printf 'get "%s" "$SAVERS/%s"\n' "$name" "$name" ;;
      *koplugin*.zip)
        # The plugin's own folder is the marker: <name>.koplugin/
        inner="$(unzip -Z1 "$f" 2>/dev/null | head -1 | cut -d/ -f1)"
        printf 'get "%s" "/mnt/us/%s"\n' "$name" "$name"
        printf 'unpack "/mnt/us/%s" "$PLUGINS" "$PLUGINS/%s"\n' "$name" "${inner:-$name}" ;;
      *.zip)
        # Marker must be the first real FILE, not the first directory: archives
        # that unpack into documents/ or extensions/ would otherwise look
        # already-installed forever, since those always exist on a Kindle.
        marker="$(unzip -Z1 "$f" 2>/dev/null | grep -v '/$' | head -1)"
        printf 'get "%s" "/mnt/us/%s"\n' "$name" "$name"
        printf 'unpack "/mnt/us/%s" "/mnt/us" "/mnt/us/%s"\n' "$name" "${marker:-$name}" ;;
      *)
        printf 'get "%s" "/mnt/us/%s"\n' "$name" "$name" ;;
    esac
  done
  shopt -u nullglob

  echo ''
  echo 'echo ""'
  echo 'echo "done: $ok new, $skip skipped, $fail failed"'
  echo '[ "$fail" -eq 0 ] || exit 1'
} > "$INSTALLER"

chmod +x "$INSTALLER"

file_count=$(find "$DIR" -maxdepth 1 -type f ! -name '_install.sh' | wc -l | tr -d ' ')

echo -e "${CYAN}Serving${NC} $DIR  (${file_count} file(s))"
echo -e "${CYAN}at${NC}      $BASE"
echo ""
echo -e "${YELLOW}On the Kindle, in kTerm — one line, that's it:${NC}"
echo ""
echo -e "  ${GREEN}wget -O /tmp/i.sh $BASE/_install.sh && sh /tmp/i.sh${NC}"
echo ""
echo "It creates the folders, downloads everything, unpacks any zips into the"
echo "right place, and skips whatever is already installed. Safe to re-run."
echo ""
echo -e "${GREEN}Ctrl-C to stop the server when you're done.${NC}"
echo ""

cd "$DIR" && exec python3 -m http.server "$PORT" --bind 0.0.0.0
